os: osx
osx_image: xcode7.3

before_install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - cd $ROOT/extensions && brew bundle && cd $ROOT

before_script:
  - for TEST in $ROOT/tests/*; do chmod +x $TEST; done

script:
  - bash $ROOT/tests/osx.test.sh
  - bash $ROOT/tests/nvm.test.sh
