os: osx
osx_image: xcode7.3

before_install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - cd ./extensions && brew bundle

before_script:
  - for TEST in tests/*; do chmod +x $TEST; done

script:
  - bash tests/osx.test.sh
  - bash tests/nvm.test.sh
