osx_image: xcode7.3
env: TESTDIR=./tests

before_install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - cd ./extensions && brew bundle

before_script:
  - for TEST in $(find $TESTDIR/ -name '*.test.sh'); do chmod +x $TEST done

script:
  - $TESTDIR/osx.test.sh
  - $TESTDIR/nvm.test.sh
