os: osx
osx_image: xcode7.3

before_install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - brew bundle --file="$ROOT/extensions/Brewfile"

before_script:
  - for TEST in $ROOT/tests/*; do chmod +x $TEST; done

script:
  - bash $ROOT/tests/nvm.test.sh
