os: osx
osx_image: xcode7.3

# temp-disable
# before_install:
#   - brew update
#   - brew tap Homebrew/bundle

# temp-disable
# install:
#   - cd ./extensions && brew bundle && cd ../

before_script:
  - for TEST in $ROOT/tests/*; do chmod +x $TEST; done

script:
  - bash $ROOT/tests/osx.test.sh
  - bash $ROOT/tests/nvm.test.sh
