os: osx
osx_image: xcode7.3

before_install:
  - brew update
  - brew tap Homebrew/bundle

install:
  - cd ./extensions && brew bundle && cd ../

before_script:
  - for TEST in $PWD/tests/*; do chmod +x $TEST; done

script:
  - bash $PWD/tests/osx.test.sh
  - bash $PWD/tests/nvm.test.sh
