cask_args appdir: '/Applications'

tap 'homebrew/aliases'
tap 'homebrew/completions'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/command-not-found'
tap 'caskroom/versions'
tap 'caskroom/fonts' # github.com/caskroom/homebrew-fonts

brew 'apm-bash-completion'
brew 'awscli'

#Bash 4
brew 'bash'
brew 'bash-completion@2' # github.com/scop/bash-completion (for Bash >4 use bash-completion instead)
brew 'ccat'
brew 'docker-completion'
# Install GNU core utilities (those that come with OS X are outdated)
brew 'coreutils'
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'
brew 'git'
brew 'grep'
brew 'mackup'
brew 'nano'
brew 'lua', args: ['with-completion']
brew 'luajit'
brew 'nmap'
brew 'openssl'
brew 'pyenv'
brew 'rbenv'
brew 'tcping'
brew 'mosquitto'
brew 'screen'
brew 'ssh-copy-id'
brew 'trash'
brew 'tree'
brew 'gibo'
brew 'dvm'
brew 'zsh'
brew 'zsh-completions'
brew 'wget', args: ['with-iri']
brew 'vim', args: ['with-lua', 'with-luajit', 'with-override-system-vi']
brew 'doxygen'
cask 'xquartz' #imagemagick dependency
brew 'imagemagick', args: ['with-fftw', 'with-fontconfig', 'with-ghostscript', 'with-hdri', 'with-openjpeg', 'with-liblqr', 'with-librsvg', 'with-libwmf', 'with-little-cms',  'with-openexr', 'with-pango', 'with-perl', 'with-quantum-depth-16', 'with-quantum-depth-32', 'with-quantum-depth-8', 'with-webp', 'with-x11']

# ================================= #
cask 'java'

cask 'arduino'
cask 'atom'
cask 'macdown'

cask 'iterm2'
cask 'hyper'

#docker-engine, docker-compose, docker-machine, kinematic. Brings viartualbox.
cask 'docker-toolbox'
cask 'mancy'
cask 'postman'
cask 'fastlane'
cask 'spectacle'
cask 'imageoptim'
cask 'insomnia' # insomnia.rest

cask 'sketch' #sketch app

cask 'alfred'
cask 'dash'
cask 'etcher'

cask 'suspicious-package'

cask '1password'
cask 'colorpicker-skalacolor'
cask 'dropbox'
cask 'slack'
cask 'amazon-music'
cask 'spotify' # spotify.com
cask 'skype' 

cask 'firefox'
cask 'google-chrome'
cask 'google-chrome-canary'

cask 'qlcolorcode' # github.com/n8gray/QLColorCode
cask 'qlimagesize' # github.com/Nyx0uf/qlImageSize
cask 'qlmarkdown' # github.com/toland/qlmarkdown
cask 'qlstephen' # github.com/whomwah/qlstephen
cask 'quicklook-csv' # github.com/p2/quicklook-csv
cask 'quickjson' # github.com/johan/QuickJSON

cask 'virtualbox' # virtualbox.org

# — Fonts —
cask 'font-hack'
cask 'font-ibm-plex'
