#!/usr/bin/env bash

# Install yarn from the official install script
curl -o- -L https://yarnpkg.com/install.sh | bash

# Globally add this packages array
packages=(
  commitizen
  mklicense
  speed-test
  envset
  poke-repl
  slv
  servedir
)

yarn global add ${packages[@]}
